### ISSUE TITLE
ReferenceError: Unknown plugin "babel-plugin-transform-strict-mode"

### ISSUE THREAD

**Issue by Jefreesujit** [airbnb/babel-preset-airbnb#35]
Hi,

When i m trying to build my application it breaks because of the following issue from your package.

`
ReferenceError: Unknown plugin "babel-plugin-transform-strict-mode" specified in "/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-preset-airbnb/index.js" at 1, attempted to resolve relative to "/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-preset-airbnb" (While processing preset: "/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-preset-airbnb/index.js")
error	16-Jul-2018 05:52:35	    at /usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
error	16-Jul-2018 05:52:35	    at Array.map (native)
error	16-Jul-2018 05:52:35	    at Function.normalisePlugins (/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
error	16-Jul-2018 05:52:35	    at OptionManager.mergeOptions (/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
error	16-Jul-2018 05:52:35	    at /usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
error	16-Jul-2018 05:52:35	    at /usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
error	16-Jul-2018 05:52:35	    at Array.map (native)
error	16-Jul-2018 05:52:35	    at OptionManager.resolvePresets (/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
error	16-Jul-2018 05:52:35	    at OptionManager.mergePresets (/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
error	16-Jul-2018 05:52:35	    at OptionManager.mergeOptions (/usr/local/bamboo/agent3-home/xml-data/build-dir/APP/MyApplication/Content/oppDash/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
`

I think its because of your changes yesterday. Can you help me resolve this issue?

**Comment by ljharb** [comment]
It seems like you might be running babel on your node_modules. Are you using React native, or have you configured babel to do this?

**Comment by Jefreesujit** [comment]
@ljharb hi, sorry, didnt see you reply.. Its not an react native app and yeah i ve configured it using babel. However, got it working by going back to a previous version.

**Comment by ljharb** [comment]
@Jefreesujit are you transpiling node_modules tho? babel should only be running on your own code.

**Comment by Jefreesujit** [comment]
No I don't, i do only for my own code. And it's been working till your latest update. 

If you take a look at the error logs properly.. the problem is due to "babel-plugin-transform-strict-mode" which you added as part of your latest release.

**Comment by ljharb** [comment]
ahhhhhh yes thank you :-) i see my mistake. Fix coming shortly.

**Comment by ljharb** [comment]
v2.5.3 is released. Sorry for the back and forth, I appreciate your persistence :-)
